
CREATE TABLE admins(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT NOT NULL UNIQUE,
password TEXT NOT NULL
);

CREATE TABLE articles(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL UNIQUE,
summery TEXT NOT NULL,
description TEXT NOT NULL
);
